[gcp_service_account]
type = "service_account"
project_id = "registration-422517"
private_key_id = "dc945cd889f2c86dc146a7c7e253ad803936be65"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDiLeVlubpPjtF8
LqheTDMfSHwHl86tFALpgOjTI1fwI6vWn+2XXOpu8ZDpixr7rmsZ4o/miRtNXO8r
KvxLCBCb2bpBGJT8iXAfk/JFs+P2vlHEKMiSyW7Jn8M4tABSmgcGymgM3ByCgzXp
6Xd58evqeB5ZT2peKxa6FPf1kSN5S0K6O5vL41nPh4hkNvO8IvLRmknGo2fCSers
dAxE0SXS29vLI6onG6LccLfZNph311uBcqn25H/7WQE6h6t/U/RCDJjEtgcy482C
SJYyGL+xOoHSSe8RPaSksOjB1LGq/lnMsn1MsVEICWSa5lztHfJuUJRRV8FCYe+l
wZ3cI6UXAgMBAAECggEAbU/1QJbk3rKNuFDseralNodXumu6LZgwWB4/aFv6kksL
L+2XbMIxY3FIsjbS0bTYemgvWCIHmfpCdUCPMswxCsHN7MwupWbfU8OzIdDxaj1N
U1rKpXbJHpUiSvNj/IgIwVVtuFlhRgqYMfbuEXfEp0tqj4t8QwrcLw8XUA3XcTTv
3Cx8AE2KhShiu0zA2yRPjFDQkzRLfRutG4IWICRxC14ojevGHbbNApvJzPORWTON
gwsZ7h9FwIzgQpoWrmFlpG0DTnHAFwymuuo2Lx1jhvZTkFdyM/RslUklB8lOLywE
hTO7PxBfj8rF/jpPRMYtKHMpgJaoC7bzDCJnMDnQYQKBgQD3DVvu0z6r9kfOknPc
EjOje7tTSAjeiafQsJChz11y5RoSvCGN5IONYRqb8y+Z7KJw+P6Jjdcj3fUHLFzF
Xzn+4TGuXDR934WB/yNi0QJui2nX2Wkdjxg3+zPgbuXiWKGsqRTNsVly59LSPbFZ
11109F1iFOSFXJJmTp8hx1xXiQKBgQDqXwF1W8CrbzetPu0isGAFR6zo6oMTUiXX
xXjxLGINvlHxTtsnOVMFxkT0d4fbUJH0SqrR68QmqN7Wg3CCg83ztv3NGyZELtBj
FXn94S318Zq32ixeITe8FNs82gSycqAFVwSBf6whC9fMypMowY353+oH//Xrlq0y
UTDHnRZPnwKBgBnyUjxz/ToMRKBiaz6qvrel0BfAEgZlSLW3RYlpAPSHMUTUc2W2
oUZg8217jf1JiAn7bKg/uF+w+QIG27ty8+Fb/17DmlO5/QiZJjtDnlDD3Zro34xW
MgH3JQymOQibrGc43tF3leBmjpK8HftEjjExVPlvHk0PWuTZzwa6LG2ZAoGASYh5
Wqro7mC8pTyDBkk0NzPfykwZx+wUN3ibk3+LXCiEaSOGmu3fYIZuiA0gsOy8flsW
8Tn5lu+Qytj+adSUv4yAYOPNw8K0WwIX/lGyK+Ib2uc22GmvpPEeQB9fLeXM0yAU
J9U42j1u/a/pL/ZaZzWbpdrm+32Q5aKXnWlp4J0CgYEAnMvJYPeDQIzg+7vwLVoJ
cnaRWcnGUx/s3eaa3452tPGqJvu2/0wmIWpaIyyNin52p/DJt50CFKrRWGwFqI3n
EPjazuk8npXMnUOYnTLg2Z7LA2K4bLdUSEfjvWLj/hpjSxYM9xwIQz11yfU3VAAl
4tICGIQ929sGRm/uonyUers=
-----END PRIVATE KEY-----
"""
client_email = "registration@registration-422517.iam.gserviceaccount.com"
client_id = "110973540146600315000"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/registration%40registration-422517.iam.gserviceaccount.com"
universe_domain = "googleapis.com"